
// This file has been generated by the GUI designer. Do not modify.
namespace MonoHotDraw
{
	public partial class SteticComponent
	{
		private global::Gtk.ScrolledWindow scrolledwindow;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoHotDraw.SteticComponent
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoHotDraw.SteticComponent";
			// Container child MonoHotDraw.SteticComponent.Gtk.Container+ContainerChild
			this.scrolledwindow = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow.CanFocus = true;
			this.scrolledwindow.Name = "scrolledwindow";
			this.scrolledwindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.Add (this.scrolledwindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
