
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FiguresAction;

	private global::Gtk.Action AddClassAction;

	private global::Gtk.Action EditAction;

	private global::Gtk.Action UndoAction;

	private global::Gtk.Action RedoAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Toolbar toolbar1;

	private global::MonoHotDraw.SteticComponent mhdcanvas;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FiguresAction = new global::Gtk.Action ("FiguresAction", global::Mono.Unix.Catalog.GetString ("Figures"), null, null);
		this.FiguresAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Figures");
		w1.Add (this.FiguresAction, null);
		this.AddClassAction = new global::Gtk.Action ("AddClassAction", global::Mono.Unix.Catalog.GetString ("Add Class"), null, null);
		this.AddClassAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Class");
		w1.Add (this.AddClassAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.UndoAction = new global::Gtk.Action ("UndoAction", global::Mono.Unix.Catalog.GetString ("_Deshacer"), null, "gtk-undo");
		this.UndoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Deshacer");
		w1.Add (this.UndoAction, null);
		this.RedoAction = new global::Gtk.Action ("RedoAction", global::Mono.Unix.Catalog.GetString ("_Rehacer"), null, "gtk-redo");
		this.RedoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Rehacer");
		w1.Add (this.RedoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FiguresAction' action='FiguresAction'><menuitem name='AddClassAction' action='AddClassAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='UndoAction' action='UndoAction'/><menuitem name='RedoAction' action='RedoAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'/></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.toolbar1.IconSize = ((global::Gtk.IconSize)(3));
		this.vbox2.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.toolbar1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.mhdcanvas = new global::MonoHotDraw.SteticComponent ();
		this.mhdcanvas.Events = ((global::Gdk.EventMask)(256));
		this.mhdcanvas.Name = "mhdcanvas";
		this.vbox2.Add (this.mhdcanvas);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.mhdcanvas]));
		w4.Position = 2;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 446;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AddClassAction.Activated += new global::System.EventHandler (this.OnAddClassActionActivated);
		this.UndoAction.Activated += new global::System.EventHandler (this.OnUndoActionActivated);
		this.RedoAction.Activated += new global::System.EventHandler (this.OnRedoActionActivated);
	}
}
