
// This file has been generated by the GUI designer. Do not modify.
namespace MonoHotDraw.Samples
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FiguresAction;

		private global::Gtk.Action AddAnalogClockAction;

		private global::Gtk.Action AddDigitalClockAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoHotDraw.Samples.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FiguresAction = new global::Gtk.Action ("FiguresAction", global::Mono.Unix.Catalog.GetString ("Figures"), null, null);
			this.FiguresAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Figures");
			w1.Add (this.FiguresAction, null);
			this.AddAnalogClockAction = new global::Gtk.Action ("AddAnalogClockAction", global::Mono.Unix.Catalog.GetString ("Add Analog Clock"), null, null);
			this.AddAnalogClockAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Analog Clock");
			w1.Add (this.AddAnalogClockAction, null);
			this.AddDigitalClockAction = new global::Gtk.Action ("AddDigitalClockAction", global::Mono.Unix.Catalog.GetString ("Add Digital Clock"), null, null);
			this.AddDigitalClockAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Digital Clock");
			w1.Add (this.AddDigitalClockAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MonoHotDraw.Samples.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MonoHotDraw.Samples.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FiguresAction' action='FiguresAction'><menuitem name='AddAnalogClockAction' action='AddAnalogClockAction'/><menuitem name='AddDigitalClockAction' action='AddDigitalClockAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.scrolledwindow1]));
			w3.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.AddAnalogClockAction.Activated += new global::System.EventHandler (this.OnAddAnalogClockActionActivated);
			this.AddDigitalClockAction.Activated += new global::System.EventHandler (this.OnAddDigitalClockActionActivated);
		}
	}
}
