
// This file has been generated by the GUI designer. Do not modify.
namespace MonoHotDraw.Samples
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action actoriconAction;

		private global::Gtk.Action actoriconAction1;

		private global::Gtk.Action actoriconAction2;

		private global::Gtk.Action connectioniconAction;

		private global::Gtk.Action usecaseiconAction;

		private global::Gtk.Action commenticonAction;

		private global::Gtk.Action FiguresAction;

		private global::Gtk.Action AddActor;

		private global::Gtk.Action AddUseCase;

		private global::Gtk.Action AddConnection;

		private global::Gtk.Action AddComment;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action QuitAction;

		private global::Gtk.VBox vbox2;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.ScrolledWindow scrolledwindow;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoHotDraw.Samples.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.actoriconAction = new global::Gtk.Action ("actoriconAction", null, null, "actor_icon");
			w1.Add (this.actoriconAction, null);
			this.actoriconAction1 = new global::Gtk.Action ("actoriconAction1", null, null, "actor_icon");
			w1.Add (this.actoriconAction1, null);
			this.actoriconAction2 = new global::Gtk.Action ("actoriconAction2", null, null, "actor_icon");
			w1.Add (this.actoriconAction2, null);
			this.connectioniconAction = new global::Gtk.Action ("connectioniconAction", null, null, "connection_icon");
			w1.Add (this.connectioniconAction, null);
			this.usecaseiconAction = new global::Gtk.Action ("usecaseiconAction", null, null, "usecase_icon");
			w1.Add (this.usecaseiconAction, null);
			this.commenticonAction = new global::Gtk.Action ("commenticonAction", null, null, "comment_icon");
			w1.Add (this.commenticonAction, null);
			this.FiguresAction = new global::Gtk.Action ("FiguresAction", global::Mono.Unix.Catalog.GetString ("Figures"), null, null);
			this.FiguresAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Figures");
			w1.Add (this.FiguresAction, null);
			this.AddActor = new global::Gtk.Action ("AddActor", global::Mono.Unix.Catalog.GetString ("Add Actor"), null, null);
			this.AddActor.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Actor");
			w1.Add (this.AddActor, null);
			this.AddUseCase = new global::Gtk.Action ("AddUseCase", global::Mono.Unix.Catalog.GetString ("Add UseCase"), null, null);
			this.AddUseCase.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add UseCase");
			w1.Add (this.AddUseCase, null);
			this.AddConnection = new global::Gtk.Action ("AddConnection", global::Mono.Unix.Catalog.GetString ("Add Connection"), null, null);
			this.AddConnection.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Connection");
			w1.Add (this.AddConnection, null);
			this.AddComment = new global::Gtk.Action ("AddComment", global::Mono.Unix.Catalog.GetString ("Add Comment"), null, null);
			this.AddComment.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Comment");
			w1.Add (this.AddComment, null);
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("_Salir"), null, "gtk-quit");
			this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Salir");
			w1.Add (this.QuitAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "MonoHotDraw.Samples.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MonoHotDraw.Samples.MainWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='FiguresAction' action='FiguresAction'><menuitem name='AddActor' action='AddActor'/><menuitem name='AddUseCase' action='AddUseCase'/><menuitem name='AddConnection' action='AddConnection'/><menuitem name='AddComment' action='AddComment'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox2.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow.CanFocus = true;
			this.scrolledwindow.Name = "scrolledwindow";
			this.scrolledwindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox2.Add (this.scrolledwindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow]));
			w3.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 446;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.AddActor.Activated += new global::System.EventHandler (this.OnAddActorActivated);
			this.AddUseCase.Activated += new global::System.EventHandler (this.OnAddUseCaseActivated);
			this.AddConnection.Activated += new global::System.EventHandler (this.OnAddConnectionActivated);
			this.AddComment.Activated += new global::System.EventHandler (this.OnAddCommentActivated);
			this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		}
	}
}
