
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FiguresAction;
	private global::Gtk.Action AddClassFigureAction;
	private global::Gtk.Action AddStackFigureAction;
	private global::Gtk.Action AddMemberGroupAction;
	private global::Gtk.Action AddSimpleTextFigureAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::MonoHotDraw.SteticComponent mhdcanvas;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FiguresAction = new global::Gtk.Action ("FiguresAction", global::Mono.Unix.Catalog.GetString ("Figures"), null, null);
		this.FiguresAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Figures");
		w1.Add (this.FiguresAction, null);
		this.AddClassFigureAction = new global::Gtk.Action ("AddClassFigureAction", global::Mono.Unix.Catalog.GetString ("Add Class Figure"), null, null);
		this.AddClassFigureAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add Class Figure");
		w1.Add (this.AddClassFigureAction, null);
		this.AddStackFigureAction = new global::Gtk.Action ("AddStackFigureAction", global::Mono.Unix.Catalog.GetString ("Add StackFigure"), null, null);
		this.AddStackFigureAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add StackFigure");
		w1.Add (this.AddStackFigureAction, null);
		this.AddMemberGroupAction = new global::Gtk.Action ("AddMemberGroupAction", global::Mono.Unix.Catalog.GetString ("Add MemberGroup"), null, null);
		this.AddMemberGroupAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add MemberGroup");
		w1.Add (this.AddMemberGroupAction, null);
		this.AddSimpleTextFigureAction = new global::Gtk.Action ("AddSimpleTextFigureAction", global::Mono.Unix.Catalog.GetString ("Add SimpleTextFigure"), null, null);
		this.AddSimpleTextFigureAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add SimpleTextFigure");
		w1.Add (this.AddSimpleTextFigureAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FiguresAction' action='FiguresAction'><menuitem name='AddClassFigureAction' action='AddClassFigureAction'/><menuitem name='AddStackFigureAction' action='AddStackFigureAction'/><menuitem name='AddMemberGroupAction' action='AddMemberGroupAction'/><menuitem name='AddSimpleTextFigureAction' action='AddSimpleTextFigureAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.mhdcanvas = new global::MonoHotDraw.SteticComponent ();
		this.mhdcanvas.Events = ((global::Gdk.EventMask)(256));
		this.mhdcanvas.Name = "mhdcanvas";
		this.vbox1.Add (this.mhdcanvas);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mhdcanvas]));
		w3.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AddClassFigureAction.Activated += new global::System.EventHandler (this.OnAddClassFigureActionActivated);
		this.AddStackFigureAction.Activated += new global::System.EventHandler (this.OnAddStackFigureActionActivated);
		this.AddMemberGroupAction.Activated += new global::System.EventHandler (this.OnAddMemberGroupActionActivated);
		this.AddSimpleTextFigureAction.Activated += new global::System.EventHandler (this.OnAddSimpleTextFigureActionActivated);
	}
}
